### ISSUE TITLE
VM does not boot or get IP from dhcp

### ISSUE THREAD

**Issue by rhtyd** [alpinelinux/alpine-make-vm-image#13]
By default eth0 is DOWN for some reason, I've to enable it manually and then call udhcpc to get IP address. Any pointers @jirutka thanks.

**Comment by rhtyd** [comment]
![Screenshot from 2020-07-13 16-23-06](https://user-images.githubusercontent.com/95203/87296917-30b74380-c525-11ea-97ee-52e0c50ca113.png)

**Comment by rhtyd** [comment]
In another fresh run it worked, closing

**Comment by tryauuum** [comment]
absolutely no networking for me as well. Same symptoms as @rohityadavcloud described, `eth0` is down, but if you manually bring it up you can actually have working network. `/etc/network/interfaces` is not present in generated image.

the command I used to generate image:
```
./alpine-make-vm-image --image-format raw --serial-console --image-size 400M /var/lib/libvirt/images/alpine.raw
```

**Comment by tryauuum** [comment]
for me the following change does fix the networking issue https://github.com/tryauuum/alpine-make-vm-image/commit/0314ee90471b9c53d6c3796fc08c59e6f86262b7

**Comment by jirutka** [comment]
`alpine-make-vm-image` doesn’t set up networking, it’s up to you to provide it with a script that will configure whatever you need for your environment.
