### ISSUE TITLE
Image with xfs does not work

### ISSUE THREAD

**Issue by BernhardGruen** [alpinelinux/alpine-make-vm-image#2]
I have found a bug. I tried to create an image with xfs file system. But the system does not boot when I chose xfs.
I also have a possible patch ready.
But it creates a partition. It is unfortunately needed as it seems.
That would maybe also help with #1.

**Comment by zacksiri** [comment]
Looking forward to a PR

**Comment by jirutka** [comment]
If the problem was caused by a conflict between the extlinux and XFS headers due to a lack of the partition table, then e0feeb445ee4349546a8835b20b29e22de02dfa6 resolves this issue.
