### ISSUE TITLE
lts kernel flavor results in broken /sysroot mount path

### ISSUE THREAD

**Issue by natesales** [alpinelinux/alpine-make-vm-image#23]
When building an image with the `lts` kernel-flavor, the resulting image isn't able to find the root fs to mount.

![image](https://user-images.githubusercontent.com/20391440/117529206-1dc9a000-af8b-11eb-869b-183decdd4b25.png)

I'm using `sudo ./alpine-make-vm-image --image-format qcow2 --kernel-flavor lts alpine-test.qcow2` to build the image and `sudo kvm -smp 8 -drive file=alpine-test.qcow2` to test in qemu. Replacing the kernel-flavor with the default `virt` kernel works just fine.

**Comment by petrm** [comment]
This is caused by running mkinitfs before installing kernel. The modules are missing in the temporary root, because they have not been installed yet.
