### ISSUE TITLE
building with --rootfs btrfs fails

### ISSUE THREAD

**Issue by xfnw** [alpinelinux/alpine-make-vm-image#28]
logs:
```
> Setting up extlinux bootloader
(1/3) Installing mtools (4.0.36-r0)
(2/3) Installing blkid (2.37.2-r1)
(3/3) Installing syslinux (6.04_pre1-r9)
OK: 47 MiB in 37 packages
/boot is device /dev/nbd14
Warning: unable to obtain device geometry (defaulting to 64 heads, 32 sectors)
         (on hard disks, this is usually harmless.)
/dev/nbd14 disconnected
```

it fails at [lines 275-276](https://github.com/alpinelinux/alpine-make-vm-image/blob/master/alpine-make-vm-image#L275-276)

```sh
	chroot "$mnt" update-extlinux --warn-only 2>&1 \
		| grep -Fv 'extlinux: cannot open device /dev' >&2
```

i am not entirely sure what the grep is for, but when omitting it the image builds fine (and boots fine too)

**Comment by jirutka** [comment]
The grep is here to hide that misleading error message `extlinux: cannot open device /dev`. The problem is that it exits with non-zero status when this message is not found, which is a bug.
